name: "Flake Update"
on:
  schedule:
    - cron: '30 3 * * 0'
  workflow_dispatch:
jobs:
   upgrades:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: configure git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: perform flake update
      run: |
        nix flake update
        nix build
    - run: |
        git add .
        git commit -m "Flake Update" && git push origin || echo "nothing to do"
